#!/bin/bash
set -euo pipefail

. .env

RUN_SCRIPT="/usr/local/ai_batch/run_gist_batch.sh"
GIST_URL=$SYNC_DAILY_CRON_GIST_URL

TMP_LIST=$(mktemp /tmp/batch_list.XXXXXX.txt)
curl -sS "$GIST_URL" -o "$TMP_LIST"

{
  echo "# Auto-generated by sync_cron_from_gist.sh ($(date))"
  while IFS= read -r line || [ -n "$line" ]; do
    # 前後空白除去
    line="$(printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    [ -z "$line" ] && continue
    case "$line" in \#*) continue ;; esac

    # 半角スペース以降は破棄
    url="${line%% *}"

    # gist raw URL 以外は拒否
    case "$url" in
      https://gist.githubusercontent.com/*/raw/*)
        echo "0 8 * * * /bin/bash -lc '$RUN_SCRIPT \"$url\"'"
        ;;
      *)
        continue
        ;;
    esac
  done < "$TMP_LIST"
} | crontab -

rm -f "$TMP_LIST"
echo "cron updated from $GIST_URL"
